# Generated by Django 4.2.28 on 2026-02-09 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MiniFWBlockedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("blocked_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("segment", models.CharField(max_length=50)),
                ("reason", models.TextField()),
                ("score", models.IntegerField()),
                ("auto_blocked", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "minifw_blocked_ips",
                "ordering": ["-blocked_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super Admin"),
                            ("ADMIN", "Admin"),
                            ("OPERATOR", "Operator"),
                            ("AUDITOR", "Auditor"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="VIEWER",
                        max_length=20,
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("HOSPITAL", "Hospital"),
                            ("SCHOOL", "School"),
                            ("GOVERNMENT", "Government"),
                            ("FINANCE", "Finance"),
                            ("LEGAL", "Legal"),
                            ("ESTABLISHMENT", "Establishment"),
                        ],
                        default="ESTABLISHMENT",
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("is_locked", models.BooleanField(default=False)),
                ("failed_login_attempts", models.IntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("must_change_password", models.BooleanField(default=False)),
                ("last_password_change", models.DateTimeField(blank=True, null=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "minifw_user_profiles",
            },
        ),
        migrations.CreateModel(
            name="MiniFWEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("segment", models.CharField(db_index=True, max_length=50)),
                ("client_ip", models.GenericIPAddressField(db_index=True)),
                ("domain", models.CharField(db_index=True, max_length=255)),
                ("action", models.CharField(db_index=True, max_length=20)),
                ("score", models.IntegerField()),
                ("reasons", models.JSONField(default=list)),
            ],
            options={
                "db_table": "minifw_events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "action"],
                        name="minifw_even_timesta_762f9c_idx",
                    ),
                    models.Index(
                        fields=["client_ip", "-timestamp"],
                        name="minifw_even_client__bfaa62_idx",
                    ),
                    models.Index(
                        fields=["segment", "-timestamp"],
                        name="minifw_even_segment_26b361_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("username", models.CharField(db_index=True, max_length=150)),
                ("user_role", models.CharField(max_length=50)),
                ("user_sector", models.CharField(blank=True, max_length=50, null=True)),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("severity", models.CharField(default="info", max_length=20)),
                (
                    "resource_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("before_value", models.JSONField(blank=True, null=True)),
                ("after_value", models.JSONField(blank=True, null=True)),
                ("extra_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "minifw_audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["severity", "-timestamp"],
                        name="minifw_audi_severit_b59904_idx",
                    )
                ],
            },
        ),
    ]
