# Generated by Django 4.2.14 on 2025-12-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AsnTrustConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asn_number", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("score", models.FloatField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AsnInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("asn_number", models.CharField(max_length=50)),
                ("trust_score", models.FloatField()),
                ("asn_description", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_latest", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ip_address", "is_latest"],
                        name="asn_asninfo_ip_addr_2f5ec1_idx",
                    )
                ],
            },
        ),
    ]
