# Generated by Django 5.2.4 on 2025-12-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InternalIPList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "list_type",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")], max_length=10
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="IpReputation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("scores", models.JSONField()),
                ("reputation_score", models.FloatField()),
                ("isp", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("is_tor", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
