"""
Django settings for ritapi_v_sentinel project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
import environ
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Init environ
env = environ.Env()

# Load unified environment file
env_file = Path("/etc/ritapi/vsentinel.env")
local_env = BASE_DIR / ".env"

if env_file.exists():
    environ.Env.read_env(env_file)
elif local_env.exists():
    environ.Env.read_env(local_env)
else:
    # Allow running without env file for some cases or raise meaningful error
    if 'test' not in sys.argv:
         raise Exception(f"Unified env file not found at: {env_file} or {local_env}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    
    'authentication',
    'asn',
    'ip_reputation',
    'alert',
    'blocking',
    'json_schema',
    'log_channel',
    'minifw',
    
    'ops',
    'ops.ops_asn',
    'ops.ops_iprep',
    'ops.ops_json',
    'ops.ops_alert',
    'ops.ops_blocking',
    'ops.ops_geoblock',
]

MIDDLEWARE = [
    'middlewares.rate_limit.RateLimiterMiddleware',
    'middlewares.security_enforcement.SecurityEnforcementMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'authentication.middleware.OpsAuthMiddleware',
]

ROOT_URLCONF = 'ritapi_v_sentinel.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates", 
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'ritapi_v_sentinel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

_database_url = env("DATABASE_URL", default="")
if _database_url:
    DATABASES = {
        'default': dj_database_url.parse(_database_url, conn_max_age=600),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env("DB_NAME"),
            'USER': env("DB_USER"),
            'PASSWORD': env("DB_PASSWORD"),
            'HOST': env("DB_HOST"),
            'PORT': env("DB_PORT"),
            'TEST': {
                'NAME': 'ritapi_v_sentinel_test_db',
            },
        }
    }

if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# Security Enforcement Configuration
# ============================================
MAX_JSON_BODY = 2 * 1024 * 1024  # 2 MB
ENFORCE_JSON_CT = True

# Paths exempted from global JSON enforcement (mostly HTML/UI paths)
SECURITY_ENFORCEMENT_EXCLUDED_PATHS = [
    "/admin/",
    "/static/",
    "/favicon.ico",
    "/robots.txt",
    "/login/",
    "/auth/login/",
    "/auth/logout/",
    "/logout/",
    "/healthz",
    "/readyz",
    # MiniFW dashboard form-based endpoints (use application/x-www-form-urlencoded)
    "/ops/minifw/policy/",
    "/ops/minifw/feeds/",
    "/ops/minifw/blocked-ips/",
    "/ops/minifw/service/",
    # Ops sub-app form-based endpoints
    "/change-password/",
    "/ops/asn/asn-checker/",
    "/ops/asn/asn-update-score/",
    "/ops/ip-reputation/",
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'ops_dashboard'
LOGOUT_REDIRECT_URL = 'login'