# Generated by Django 4.2.14 on 2025-12-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JsonSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "endpoint",
                    models.CharField(
                        help_text="Path prefix or full path, e.g. /api/data",
                        max_length=255,
                    ),
                ),
                (
                    "method",
                    models.CharField(help_text="GET, POST, etc.", max_length=10),
                ),
                ("schema_json", models.JSONField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "version",
                    models.CharField(
                        default="v1",
                        help_text="Schema version, e.g., v1, v2-beta",
                        max_length=32,
                    ),
                ),
                (
                    "rollout_mode",
                    models.CharField(
                        choices=[
                            ("monitor", "Monitor only"),
                            ("enforce", "Strict enforcement"),
                        ],
                        default="monitor",
                        help_text="If enforce, invalid schema will be blocked. If monitor, only logged.",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("endpoint", "method", "version")},
            },
        ),
    ]
